packages:
  # all packages in subdirs of components/
  - "components/**"
  # The doc for salix-ui in subdirs of webpage
  - "webpage/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
