packages:
  # all packages in subdirs of components/
  - "salix-ui/**"
  # The doc for salix-ui in subdirs of webpage
  - "salix-ui-docs/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
